import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider,  } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from '@mui/material/styles'
import theme from './theme'
import Navbar from "./navbar";
import "./globals.css";
import './i18next'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <Navbar />
          {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
